// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Catalog struct {
	ID        string  `json:"id"`
	ProductID *string `json:"product_id"`
	UnitPrice int32   `json:"unit_price"`
}

type Category struct {
	ID                  string `json:"id"`
	CategoryName        string `json:"category_name"`
	CategoryDescription string `json:"category_description"`
}

type Product struct {
	ID          string `json:"id"`
	CategoryID  string `json:"category_id"`
	ProductName string `json:"product_name"`
	Quantity    int32  `json:"quantity"`
}

type Purchase struct {
	ID         string           `json:"id"`
	ProductID  string           `json:"product_id"`
	TotalPrice int32            `json:"total_price"`
	Quantity   int32            `json:"quantity"`
	VendorID   *string          `json:"vendor_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Sale struct {
	ID        string           `json:"id"`
	ProductID string           `json:"product_id"`
	UnitPrice int32            `json:"unit_price"`
	Quantity  int32            `json:"quantity"`
	CreateAt  pgtype.Timestamp `json:"create_at"`
	CashierID *string          `json:"cashier_id"`
}

type Vendor struct {
	ID          string  `json:"id"`
	VendorName  string  `json:"vendor_name"`
	Description *string `json:"description"`
}
