// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	CreateCatalog(ctx context.Context, arg CreateCatalogParams) (Catalog, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetCatalog(ctx context.Context) ([]GetCatalogRow, error)
	LoadTime(ctx context.Context) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
