// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	CreateBlockSale(ctx context.Context, arg CreateBlockSaleParams) (BSale, error)
	CreateBlocksProduct(ctx context.Context, arg CreateBlocksProductParams) (BProduct, error)
	CreateCatalog(ctx context.Context, arg CreateCatalogParams) (Catalog, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateMaterialPurchase(ctx context.Context, arg CreateMaterialPurchaseParams) (BPurchase, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionMaterials(ctx context.Context, arg CreateSessionMaterialsParams) (SessionMaterial, error)
	CreateSessionProducts(ctx context.Context, arg CreateSessionProductsParams) (SessionProduct, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetCatalog(ctx context.Context) ([]GetCatalogRow, error)
	LoadTime(ctx context.Context) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
