// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	CountSalesTransactions(ctx context.Context) (int64, error)
	CreateBlockSale(ctx context.Context, arg CreateBlockSaleParams) (BSale, error)
	CreateBlocksProduct(ctx context.Context, arg CreateBlocksProductParams) (BProduct, error)
	CreateCatalog(ctx context.Context, arg CreateCatalogParams) (Catalog, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateMaterialPurchase(ctx context.Context, arg CreateMaterialPurchaseParams) (BPurchase, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionMaterials(ctx context.Context, arg CreateSessionMaterialsParams) (SessionMaterial, error)
	CreateSessionProducts(ctx context.Context, arg CreateSessionProductsParams) (SessionProduct, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	DeleteBlockProduct(ctx context.Context, id string) error
	DeleteBlockPurchase(ctx context.Context, id string) error
	DeleteBlockSale(ctx context.Context, id string) error
	DeleteCatalog(ctx context.Context, id string) error
	DeleteCategory(ctx context.Context, id string) error
	DeleteMaterial(ctx context.Context, id string) error
	DeletePurchase(ctx context.Context, id string) error
	DeleteSale(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionMaterial(ctx context.Context, arg DeleteSessionMaterialParams) error
	DeleteSessionProduct(ctx context.Context, arg DeleteSessionProductParams) error
	DeleteTeam(ctx context.Context, id string) error
	Deleteproduct(ctx context.Context, id string) error
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetAllPurchases(ctx context.Context) ([]GetAllPurchasesRow, error)
	GetAllSales(ctx context.Context) ([]GetAllSalesRow, error)
	GetAllVendors(ctx context.Context) ([]Vendor, error)
	GetBlockSales(ctx context.Context) ([]GetBlockSalesRow, error)
	GetBlocksProducts(ctx context.Context) ([]GetBlocksProductsRow, error)
	GetCatalog(ctx context.Context) ([]GetCatalogRow, error)
	GetMaterialPurchases(ctx context.Context) ([]GetMaterialPurchasesRow, error)
	GetMaterials(ctx context.Context) ([]Material, error)
	GetSessionMaterials(ctx context.Context) ([]GetSessionMaterialsRow, error)
	GetSessionProducts(ctx context.Context) ([]GetSessionProductsRow, error)
	GetSessions(ctx context.Context) ([]Session, error)
	GetTeams(ctx context.Context) ([]Team, error)
	LoadTime(ctx context.Context) (interface{}, error)
	// -- name: LogIn :one
	// INSERT INTO "users" (email, password)
	// VALUES ($1, $2)
	// RETURNING *;
	SelectRequestedUser(ctx context.Context, email string) (SelectRequestedUserRow, error)
	Top5BestSellingProductsByRevenue(ctx context.Context) ([]Top5BestSellingProductsByRevenueRow, error)
	TotalSales(ctx context.Context) (int64, error)
	// b_products
	UpdateBlockProduct(ctx context.Context, arg UpdateBlockProductParams) (BProduct, error)
	// b_purchases
	UpdateBlockPurchase(ctx context.Context, arg UpdateBlockPurchaseParams) (BPurchase, error)
	// b_sales
	UpdateBlockSale(ctx context.Context, arg UpdateBlockSaleParams) (BSale, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	// materials
	UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdatePurchase(ctx context.Context, arg UpdatePurchaseParams) (Purchase, error)
	UpdateSales(ctx context.Context, arg UpdateSalesParams) (Sale, error)
	// sessions
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	// session_materials
	UpdateSessionMaterial(ctx context.Context, arg UpdateSessionMaterialParams) (SessionMaterial, error)
	// session_products
	UpdateSessionProduct(ctx context.Context, arg UpdateSessionProductParams) (SessionProduct, error)
	// teams
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
